const productos = [
    {
      title: "Colaless / Elastico Glitter",
      material: "ALGODON Y LYCRA",
      materialAdicional: "Elástico lateral de lurex ",
      price: 1000,
      image: "./conjunto.bralette.jpg",
      category: "Colaless",
      description: "Sus breteles regulables, la convierten en una prenda versatil y super adaptable al cuerpo.",
      generalDescription: "El precio corresponde a una docena, las cuales vienen surtidas y sin elección de colores.",
      stock: 9,
      initial: 5,
      id: 1,
    },
    {
      title: "Culotte",
      material: "ALGODON Y LYCRA",
      materialAdicional: "Lorem ipsum dolor sit amet.",   
      price: 1000, 
      image: "./culote-estampado.jpeg",
      category: "Culottes",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima neque iusto amet, odio ut..",
      generalDescription: "El precio corresponde a una docena, las cuales vienen surtidas y sin elección de colores.",
      stock: 6,
      initial: 3,
      id: 2,
    },
    {
      title: "Vedetina",
      material: "ALGODON Y LYCRA",
      materialAdicional: "Lorem ipsum dolor sit amet.",   
      price: 1000,  
      image: "./vedetinas2.jpeg",
      category: "Vedetinas",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima neque iusto amet, odio ut.",
      generalDescription: "El precio corresponde a una docena, las cuales vienen surtidas y sin elección de colores.",
      stock: 4,
      initial: 2,
      id: 3,
    },
    {
      title: "Vedetina",
      material: "ALGODON Y LYCRA",
      materialAdicional: "Lorem ipsum dolor sit amet.",   
      price: 1000,   
      image: "./vedetinas.jpeg",
      category: "Vedetinas",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi minima neque iusto amet, odio ut.",
      generalDescription: "El precio corresponde a una docena, las cuales vienen surtidas y sin elección de colores.",
      stock: 5,
      initial: 1,
      id: 4,
    },
  ];
  
  export default productos;